# Generated by Django 5.2.6 on 2025-10-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title_icon', models.CharField(default='tji-box', help_text='Font Awesome yoki maxsus ikon klassi', max_length=50, verbose_name='Sub-sarlavha ikona')),
                ('sub_title_text', models.CharField(default='Qarshi shahridagi', max_length=200, verbose_name='Sub-sarlavha matni')),
                ('main_title_line1', models.CharField(default='Special-', max_length=100, verbose_name='Asosiy sarlavha 1-qator')),
                ('main_title_line2', models.CharField(default='Certificate', max_length=100, verbose_name='Asosiy sarlavha 2-qator')),
                ('main_title_small', models.CharField(default='labaratoriyasi.', max_length=100, verbose_name='Sarlavha kichik matni')),
                ('button_text', models.CharField(default='Biz Haqimizda', max_length=100, verbose_name='Tugma matni')),
                ('button_link', models.CharField(default='#', help_text='URL yoki slug', max_length=255, verbose_name='Tugma havolasi')),
                ('button_icon', models.CharField(default='tji-arrow-right-long', help_text='Font Awesome yoki maxsus ikon klassi', max_length=50, verbose_name='Tugma ikona')),
                ('phone_number', models.CharField(default='+998942025511', max_length=20, verbose_name='Telefon raqami')),
                ('phone_icon', models.CharField(default='tji-phone', max_length=50, verbose_name='Telefon ikona')),
                ('hero_image', models.ImageField(help_text='Banner uchun asosiy rasm', upload_to='banner/hero/', verbose_name='Asosiy rasm')),
                ('marquee_text1', models.CharField(default='Special', max_length=50, verbose_name='Marquee matni 1')),
                ('marquee_text2', models.CharField(default='Certificate', max_length=50, verbose_name='Marquee matni 2')),
                ('growth_image', models.ImageField(help_text='Growth box uchun rasm', upload_to='banner/growth/', verbose_name="O'sish rasmi")),
                ('director_name', models.CharField(default='Asliddin Abdujabborov', max_length=100, verbose_name='Direktor ismi')),
                ('director_designation', models.CharField(default='Direktor', max_length=100, verbose_name='Direktor lavozimi')),
                ('bg_shape_1', models.ImageField(blank=True, null=True, upload_to='banner/shapes/', verbose_name='Fon shakli 1')),
                ('bg_shape_2', models.ImageField(blank=True, null=True, upload_to='banner/shapes/', verbose_name='Fon shakli 2')),
                ('scroll_text', models.CharField(default='Pastga', max_length=50, verbose_name='Scroll tugmasi matni')),
                ('scroll_link', models.CharField(default='#choose', max_length=255, verbose_name='Scroll havolasi')),
                ('scroll_icon', models.CharField(default='tji-arrow-down-long', max_length=50, verbose_name='Scroll ikona')),
                ('is_active', models.BooleanField(default=True, help_text='Banner faol yoki faol emasligini belgilaydi', verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': "Banner bo'limi",
                'verbose_name_plural': "Banner bo'limlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
