# Generated by Django 5.2.6 on 2025-10-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kompaniya yoki tashkilot nomi', max_length=200, verbose_name='Mijoz nomi')),
                ('logo', models.ImageField(help_text='Mijoz logotipi (webp formatida tavsiya etiladi)', upload_to='clients/logos/', verbose_name='Logo')),
                ('order', models.PositiveIntegerField(default=0, help_text="Kichik raqam birinchi ko'rsatiladi", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, help_text="Logotip ko'rsatilsinmi?", verbose_name='Faolmi?')),
                ('website_url', models.URLField(blank=True, help_text='Mijozning veb-sayti (ixtiyoriy)', max_length=500, null=True, verbose_name='Veb-sayt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Mijoz logotipi',
                'verbose_name_plural': 'Mijozlar logotiplari',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
