# Generated by Django 5.2.6 on 2025-10-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_clientlogo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannersection',
            options={'ordering': ['-created_at'], 'verbose_name': '1. Banner', 'verbose_name_plural': '1. Bannerlar'},
        ),
        migrations.AlterModelOptions(
            name='clientlogo',
            options={'ordering': ['order', '-created_at'], 'verbose_name': '2. Hamkor', 'verbose_name_plural': '2. Hamkorlar'},
        ),
    ]
