# Generated by Django 5.2.6 on 2025-10-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_bannersection_options_alter_clientlogo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Font Awesome yoki maxsus ikon klassi (masalan: tji-innovative)', max_length=50, verbose_name='Ikona')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(help_text='Kartochka matni', verbose_name='Tavsif')),
                ('button_text', models.CharField(default='Batafsil', max_length=100, verbose_name='Tugma matni')),
                ('button_link', models.CharField(default='#', help_text='URL yoki slug', max_length=255, verbose_name='Tugma havolasi')),
                ('button_icon', models.CharField(default='tji-arrow-right-long', max_length=50, verbose_name='Tugma ikona')),
                ('order', models.PositiveIntegerField(default=0, help_text="Kichik raqam birinchi ko'rsatiladi", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, help_text="Kartochka ko'rsatilsinmi?", verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Afzallik kartochkasi',
                'verbose_name_plural': 'Afzalliklar kartochkalari',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChooseSectionHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title_icon', models.CharField(default='tji-box', help_text='Font Awesome yoki maxsus ikon klassi', max_length=50, verbose_name='Sub-sarlavha ikona')),
                ('sub_title', models.CharField(default='Maxsus-sertifikat', max_length=200, verbose_name='Sub-sarlavha')),
                ('main_title', models.CharField(default='Nega aynan biz?', max_length=200, verbose_name='Asosiy sarlavha')),
                ('is_active', models.BooleanField(default=True, help_text="Bo'lim sarlavhasi faol yoki nofaol", verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Nega aynan biz? sarlavhasi',
                'verbose_name_plural': 'Nega aynan biz? sarlavhalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
