# Generated by Django 5.2.6 on 2025-10-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_choosecard_choosesectionheader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choosecard',
            options={'ordering': ['order', '-created_at'], 'verbose_name': '3. Afzalliklar', 'verbose_name_plural': '3. Afzalliklar'},
        ),
        migrations.AlterModelOptions(
            name='choosesectionheader',
            options={'ordering': ['-created_at'], 'verbose_name': '3. Afzallik sarlavhasi', 'verbose_name_plural': '3. Afzallik sarlavhalari'},
        ),
    ]
