# Generated by Django 5.2.6 on 2025-10-08 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_choosecard_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(help_text='Laboratoriya rasmi', upload_to='about/images/', verbose_name='Asosiy rasm')),
                ('progress_box_title', models.CharField(default="Ish faoliyatimiz ko'rsatkichlari", max_length=200, verbose_name="Ko'rsatkichlar sarlavhasi")),
                ('sub_title_icon', models.CharField(default='tji-lab', max_length=50, verbose_name='Sub-sarlavha ikona')),
                ('sub_title', models.CharField(default='Biz haqimizda', max_length=200, verbose_name='Sub-sarlavha')),
                ('main_title', models.TextField(default='Qarshi shahridagi ishonchli va xalqaro standartlarga mos sertifikatlash laboratoriyasi.', verbose_name='Asosiy sarlavha')),
                ('mission_title', models.CharField(default='Bizning maqsadimiz', max_length=200, verbose_name='Maqsad sarlavhasi')),
                ('mission_description', models.TextField(default='Maxsulot va xizmatlarning sifatini xalqaro standartlarga muvofiq baholab, mijozlarimizga ishonchli sertifikatlar taqdim etish.', verbose_name='Maqsad tavsifi')),
                ('mission_item1', models.CharField(default='Xalqaro talablar asosida sinov', max_length=200, verbose_name='Maqsad 1-bandı')),
                ('mission_item2', models.CharField(default='Sifat kafolati', max_length=200, verbose_name='Maqsad 2-bandı')),
                ('mission_item3', models.CharField(default='Shaffoflik va tezkorlik', max_length=200, verbose_name='Maqsad 3-bandı')),
                ('vision_title', models.CharField(default='Bizning qarashimiz', max_length=200, verbose_name='Qarashlari sarlavhasi')),
                ('vision_description', models.TextField(default="O'zbekiston va mintaqada yetakchi sertifikatlash markaziga aylanish hamda global ishonch qozonish.", verbose_name='Qarashlari tavsifi')),
                ('vision_item1', models.CharField(default='Ilmiy asoslangan yondashuv', max_length=200, verbose_name='Qarashlari 1-bandı')),
                ('vision_item2', models.CharField(default='Texnologik yangiliklarni joriy etish', max_length=200, verbose_name='Qarashlari 2-bandı')),
                ('vision_item3', models.CharField(default='Uzluksiz rivojlanish', max_length=200, verbose_name='Qarashlari 3-bandı')),
                ('button_text', models.CharField(default="Batafsil ma'lumot", max_length=100, verbose_name='Tugma matni')),
                ('button_link', models.CharField(default='/about', max_length=255, verbose_name='Tugma havolasi')),
                ('button_icon', models.CharField(default='tji-arrow-right-long', max_length=50, verbose_name='Tugma ikona')),
                ('bg_shape_1', models.ImageField(blank=True, null=True, upload_to='about/shapes/', verbose_name='Fon shakli 1')),
                ('bg_shape_2', models.ImageField(blank=True, null=True, upload_to='about/shapes/', verbose_name='Fon shakli 2')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': "Biz haqimizda bo'limi",
                'verbose_name_plural': "Biz haqimizda bo'limlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('percent', models.PositiveIntegerField(default=0, help_text='0 dan 100 gacha', verbose_name='Foiz miqdori')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('about_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_items', to='main_app.aboutsection', verbose_name="Biz haqimizda bo'limi")),
            ],
            options={
                'verbose_name': "Progress ko'rsatkichi",
                'verbose_name_plural': "Progress ko'rsatkichlari",
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
