# Generated by Django 5.2.6 on 2025-10-08 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_aboutsection_aboutprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'ordering': ['-created_at'], 'verbose_name': '4. Biz haqimizda', 'verbose_name_plural': '4. Biz haqimizda'},
        ),
    ]
