# Generated by Django 5.2.6 on 2025-10-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_aboutsection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutprogress',
            options={'ordering': ['order', '-created_at'], 'verbose_name': "4. Progress ko'rsatkichi", 'verbose_name_plural': "4. Progress ko'rsatkichlari"},
        ),
    ]
