# Generated by Django 5.2.6 on 2025-10-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_aboutprogress_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Font Awesome yoki maxsus ikon klassi (masalan: tji-service-1)', max_length=50, verbose_name='Ikona')),
                ('title', models.CharField(max_length=200, verbose_name='Xizmat nomi')),
                ('description', models.TextField(help_text="Xizmat haqida qisqacha ma'lumot", verbose_name='Tavsif')),
                ('detail_link', models.CharField(default='#', help_text='Xizmat tafsiloti sahifasiga havola', max_length=255, verbose_name='Batafsil havola')),
                ('background_image', models.ImageField(help_text='Service reveal background uchun rasm', upload_to='services/backgrounds/', verbose_name='Fon rasmi')),
                ('order', models.PositiveIntegerField(default=0, help_text="Kichik raqam birinchi ko'rsatiladi", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, help_text="Xizmat ko'rsatilsinmi?", verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': '5. TOP Servis',
                'verbose_name_plural': '5. TOP Servislar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopServiceSectionHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title_icon', models.CharField(default='tji-box', help_text='Font Awesome yoki maxsus ikon klassi', max_length=50, verbose_name='Sub-sarlavha ikona')),
                ('sub_title', models.CharField(default='Top Servislar', max_length=200, verbose_name='Sub-sarlavha')),
                ('main_title', models.CharField(default='Biz taqdim etadigan asosiy xizmatlar', max_length=300, verbose_name='Asosiy sarlavha')),
                ('button_text', models.CharField(default='Barcha xizmatlar', max_length=100, verbose_name='Tugma matni')),
                ('button_link', models.CharField(default='/services', help_text='URL yoki slug', max_length=255, verbose_name='Tugma havolasi')),
                ('button_icon', models.CharField(default='tji-arrow-right-long', max_length=50, verbose_name='Tugma ikona')),
                ('is_active', models.BooleanField(default=True, help_text="Bo'lim sarlavhasi faol yoki nofaol", verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': '5. TOP Servis Sarlavhasi',
                'verbose_name_plural': '5. TOP Servis Sarlavhasi',
                'ordering': ['-created_at'],
            },
        ),
    ]
