# Generated by Django 5.2.6 on 2025-10-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_topservice_topservicesectionheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarqueeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Marquee bo‘limida chiqadigan matn (masalan: Sifat nazorati, Xavfsizlik va hokazo).', max_length=100, verbose_name='Sarlavha')),
                ('image', models.ImageField(help_text='Marquee uchun rasm yuklang.', upload_to='marquee_images/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, help_text='Marquee elementlarini chiqish tartibini belgilang.', verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, help_text='Agar belgilanmasa, ushbu element sayt sahifasida chiqmaydi.', verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': '6. Marquee elementi',
                'verbose_name_plural': '6. Marquee elementlari',
                'ordering': ['-created_at', 'order'],
            },
        ),
    ]
