# Generated by Django 5.2.6 on 2025-10-08 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_marqueeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSectionHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title_icon', models.CharField(default='tji-award', help_text='Font Awesome yoki maxsus ikon klassi (masalan: tji-award)', max_length=50, verbose_name='Sub-sarlavha ikona')),
                ('sub_title', models.CharField(default='Bizning sertifikatlarimiz', help_text='Masalan: Bizning yutuqlarimiz, Sertifikatlarimiz va hokazo', max_length=200, verbose_name='Sub-sarlavha')),
                ('main_title', models.CharField(default='Sifat va ishonchlilikni tasdiqlovchi sertifikatlarimiz', max_length=300, verbose_name='Asosiy sarlavha')),
                ('button_text', models.CharField(default='Barcha sertifikatlar', max_length=100, verbose_name='Tugma matni')),
                ('button_link', models.CharField(default='/certificates', help_text='URL yoki slug manzilni kiriting (masalan: /certificates)', max_length=255, verbose_name='Tugma havolasi')),
                ('button_icon', models.CharField(default='tji-arrow-right-long', help_text='Tugmada chiqadigan ikona (masalan: tji-arrow-right-long)', max_length=50, verbose_name='Tugma ikona')),
                ('is_active', models.BooleanField(default=True, help_text='Agar belgilanmasa, ushbu sarlavha sayt sahifasida chiqmaydi.', verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan vaqti')),
            ],
            options={
                'verbose_name': '7. Sertifikatlar bo‘limi sarlavhasi',
                'verbose_name_plural': '7. Sertifikatlar bo‘limi sarlavhasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Masalan: Akkreditatsiya sertifikati', max_length=255, verbose_name='Sertifikat nomi')),
                ('description', models.CharField(blank=True, help_text='Masalan: Sifat kafolatini tasdiqlovchi hujjat', max_length=255, null=True, verbose_name='Sertifikat tavsifi')),
                ('image', models.ImageField(help_text='Sertifikatning rasm faylini yuklang', upload_to='certificates/', verbose_name='Sertifikat rasmi')),
                ('link', models.URLField(blank=True, help_text='Agar sertifikat haqida batafsil sahifa bo‘lsa, shu joyga link yozing', max_length=300, null=True, verbose_name='Havola')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sertifikatlar chiqarilish tartibini belgilaydi', verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, help_text='Agar belgilanmasa, ushbu sertifikat sayt sahifasida ko‘rinmaydi', verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan vaqti')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_cards', to='main_app.certificatesectionheader', verbose_name='Bo‘lim sarlavhasi')),
            ],
            options={
                'verbose_name': '7. Sertifikat kartasi',
                'verbose_name_plural': '7. Sertifikat kartalari',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
