# Generated by Django 5.2.6 on 2025-10-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_certificatesectionheader_certificatecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSectionHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title_icon', models.CharField(default='tji-news', help_text='Font Awesome yoki maxsus ikon klassi (masalan: tji-news)', max_length=50, verbose_name='Sub-sarlavha ikona')),
                ('sub_title', models.CharField(default='So‘nggi yangiliklar', help_text='Masalan: Blog, Yangiliklar, O‘quv markazi yangiliklari va hokazo', max_length=200, verbose_name='Sub-sarlavha')),
                ('main_title', models.CharField(default='Bizning markazdagi eng so‘nggi yangiliklardan xabardor bo‘ling', max_length=300, verbose_name='Asosiy sarlavha')),
                ('button_text', models.CharField(default='Barcha yangiliklar', max_length=100, verbose_name='Tugma matni')),
                ('button_link', models.CharField(default='/news', help_text='URL yoki slug manzilni kiriting (masalan: /news)', max_length=255, verbose_name='Tugma havolasi')),
                ('button_icon', models.CharField(default='tji-arrow-right-long', help_text='Tugmada chiqadigan ikona (masalan: tji-arrow-right-long)', max_length=50, verbose_name='Tugma ikona')),
                ('is_active', models.BooleanField(default=True, help_text='Agar belgilanmasa, ushbu sarlavha sayt sahifasida chiqmaydi.', verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan vaqti')),
            ],
            options={
                'verbose_name': '8. Yangiliklar bo‘limi sarlavhasi',
                'verbose_name_plural': '8. Yangiliklar bo‘limi sarlavhasi',
                'ordering': ['-created_at'],
            },
        ),
    ]
