# Generated by Django 5.2.6 on 2025-10-08 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_newssectionheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='faq/', verbose_name='Rasm')),
                ('title', models.CharField(max_length=255, verbose_name='Asosiy sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa sarlavha')),
                ('call_title', models.CharField(default='Bepul konsultatsiya', max_length=150, verbose_name='Qo‘ng‘iroq sarlavhasi')),
                ('phone_number', models.CharField(default='+998900000000', max_length=30, verbose_name='Telefon raqami')),
                ('phone_icon', models.CharField(default='tji-phone', max_length=50, verbose_name='Telefon ikonka classi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan vaqti')),
            ],
            options={
                'verbose_name': '9. FAQ sarlavhasi',
                'verbose_name_plural': '9. FAQ sarlavhalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan vaqti')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='main_app.faqheader', verbose_name='FAQ sarlavhasi')),
            ],
            options={
                'verbose_name': '9. FAQ elementi',
                'verbose_name_plural': '9. FAQ elementlari',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
