# Generated by Django 5.2.6 on 2025-11-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_faqheader_faqitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutprogress',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='aboutprogress',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='aboutprogress',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='button_text_en',
            field=models.CharField(default="Batafsil ma'lumot", max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='button_text_ru',
            field=models.CharField(default="Batafsil ma'lumot", max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='button_text_uz',
            field=models.CharField(default="Batafsil ma'lumot", max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='main_title_en',
            field=models.TextField(default='Qarshi shahridagi ishonchli va xalqaro standartlarga mos sertifikatlash laboratoriyasi.', null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='main_title_ru',
            field=models.TextField(default='Qarshi shahridagi ishonchli va xalqaro standartlarga mos sertifikatlash laboratoriyasi.', null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='main_title_uz',
            field=models.TextField(default='Qarshi shahridagi ishonchli va xalqaro standartlarga mos sertifikatlash laboratoriyasi.', null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_description_en',
            field=models.TextField(default='Maxsulot va xizmatlarning sifatini xalqaro standartlarga muvofiq baholab, mijozlarimizga ishonchli sertifikatlar taqdim etish.', null=True, verbose_name='Maqsad tavsifi'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_description_ru',
            field=models.TextField(default='Maxsulot va xizmatlarning sifatini xalqaro standartlarga muvofiq baholab, mijozlarimizga ishonchli sertifikatlar taqdim etish.', null=True, verbose_name='Maqsad tavsifi'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_description_uz',
            field=models.TextField(default='Maxsulot va xizmatlarning sifatini xalqaro standartlarga muvofiq baholab, mijozlarimizga ishonchli sertifikatlar taqdim etish.', null=True, verbose_name='Maqsad tavsifi'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_item1_en',
            field=models.CharField(default='Xalqaro talablar asosida sinov', max_length=200, null=True, verbose_name='Maqsad 1-bandı'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_item1_ru',
            field=models.CharField(default='Xalqaro talablar asosida sinov', max_length=200, null=True, verbose_name='Maqsad 1-bandı'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_item1_uz',
            field=models.CharField(default='Xalqaro talablar asosida sinov', max_length=200, null=True, verbose_name='Maqsad 1-bandı'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_item2_en',
            field=models.CharField(default='Sifat kafolati', max_length=200, null=True, verbose_name='Maqsad 2-bandı'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_item2_ru',
            field=models.CharField(default='Sifat kafolati', max_length=200, null=True, verbose_name='Maqsad 2-bandı'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_item2_uz',
            field=models.CharField(default='Sifat kafolati', max_length=200, null=True, verbose_name='Maqsad 2-bandı'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_item3_en',
            field=models.CharField(default='Shaffoflik va tezkorlik', max_length=200, null=True, verbose_name='Maqsad 3-bandı'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_item3_ru',
            field=models.CharField(default='Shaffoflik va tezkorlik', max_length=200, null=True, verbose_name='Maqsad 3-bandı'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_item3_uz',
            field=models.CharField(default='Shaffoflik va tezkorlik', max_length=200, null=True, verbose_name='Maqsad 3-bandı'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_title_en',
            field=models.CharField(default='Bizning maqsadimiz', max_length=200, null=True, verbose_name='Maqsad sarlavhasi'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_title_ru',
            field=models.CharField(default='Bizning maqsadimiz', max_length=200, null=True, verbose_name='Maqsad sarlavhasi'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='mission_title_uz',
            field=models.CharField(default='Bizning maqsadimiz', max_length=200, null=True, verbose_name='Maqsad sarlavhasi'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='progress_box_title_en',
            field=models.CharField(default="Ish faoliyatimiz ko'rsatkichlari", max_length=200, null=True, verbose_name="Ko'rsatkichlar sarlavhasi"),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='progress_box_title_ru',
            field=models.CharField(default="Ish faoliyatimiz ko'rsatkichlari", max_length=200, null=True, verbose_name="Ko'rsatkichlar sarlavhasi"),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='progress_box_title_uz',
            field=models.CharField(default="Ish faoliyatimiz ko'rsatkichlari", max_length=200, null=True, verbose_name="Ko'rsatkichlar sarlavhasi"),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='sub_title_en',
            field=models.CharField(default='Biz haqimizda', max_length=200, null=True, verbose_name='Sub-sarlavha'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='sub_title_ru',
            field=models.CharField(default='Biz haqimizda', max_length=200, null=True, verbose_name='Sub-sarlavha'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='sub_title_uz',
            field=models.CharField(default='Biz haqimizda', max_length=200, null=True, verbose_name='Sub-sarlavha'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_description_en',
            field=models.TextField(default="O'zbekiston va mintaqada yetakchi sertifikatlash markaziga aylanish hamda global ishonch qozonish.", null=True, verbose_name='Qarashlari tavsifi'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_description_ru',
            field=models.TextField(default="O'zbekiston va mintaqada yetakchi sertifikatlash markaziga aylanish hamda global ishonch qozonish.", null=True, verbose_name='Qarashlari tavsifi'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_description_uz',
            field=models.TextField(default="O'zbekiston va mintaqada yetakchi sertifikatlash markaziga aylanish hamda global ishonch qozonish.", null=True, verbose_name='Qarashlari tavsifi'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_item1_en',
            field=models.CharField(default='Ilmiy asoslangan yondashuv', max_length=200, null=True, verbose_name='Qarashlari 1-bandı'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_item1_ru',
            field=models.CharField(default='Ilmiy asoslangan yondashuv', max_length=200, null=True, verbose_name='Qarashlari 1-bandı'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_item1_uz',
            field=models.CharField(default='Ilmiy asoslangan yondashuv', max_length=200, null=True, verbose_name='Qarashlari 1-bandı'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_item2_en',
            field=models.CharField(default='Texnologik yangiliklarni joriy etish', max_length=200, null=True, verbose_name='Qarashlari 2-bandı'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_item2_ru',
            field=models.CharField(default='Texnologik yangiliklarni joriy etish', max_length=200, null=True, verbose_name='Qarashlari 2-bandı'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_item2_uz',
            field=models.CharField(default='Texnologik yangiliklarni joriy etish', max_length=200, null=True, verbose_name='Qarashlari 2-bandı'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_item3_en',
            field=models.CharField(default='Uzluksiz rivojlanish', max_length=200, null=True, verbose_name='Qarashlari 3-bandı'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_item3_ru',
            field=models.CharField(default='Uzluksiz rivojlanish', max_length=200, null=True, verbose_name='Qarashlari 3-bandı'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_item3_uz',
            field=models.CharField(default='Uzluksiz rivojlanish', max_length=200, null=True, verbose_name='Qarashlari 3-bandı'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_title_en',
            field=models.CharField(default='Bizning qarashimiz', max_length=200, null=True, verbose_name='Qarashlari sarlavhasi'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_title_ru',
            field=models.CharField(default='Bizning qarashimiz', max_length=200, null=True, verbose_name='Qarashlari sarlavhasi'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='vision_title_uz',
            field=models.CharField(default='Bizning qarashimiz', max_length=200, null=True, verbose_name='Qarashlari sarlavhasi'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='button_text_en',
            field=models.CharField(default='Biz Haqimizda', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='button_text_ru',
            field=models.CharField(default='Biz Haqimizda', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='button_text_uz',
            field=models.CharField(default='Biz Haqimizda', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='director_designation_en',
            field=models.CharField(default='Direktor', max_length=100, null=True, verbose_name='Direktor lavozimi'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='director_designation_ru',
            field=models.CharField(default='Direktor', max_length=100, null=True, verbose_name='Direktor lavozimi'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='director_designation_uz',
            field=models.CharField(default='Direktor', max_length=100, null=True, verbose_name='Direktor lavozimi'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='director_name_en',
            field=models.CharField(default='Asliddin Abdujabborov', max_length=100, null=True, verbose_name='Direktor ismi'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='director_name_ru',
            field=models.CharField(default='Asliddin Abdujabborov', max_length=100, null=True, verbose_name='Direktor ismi'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='director_name_uz',
            field=models.CharField(default='Asliddin Abdujabborov', max_length=100, null=True, verbose_name='Direktor ismi'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='main_title_line1_en',
            field=models.CharField(default='Special-', max_length=100, null=True, verbose_name='Asosiy sarlavha 1-qator'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='main_title_line1_ru',
            field=models.CharField(default='Special-', max_length=100, null=True, verbose_name='Asosiy sarlavha 1-qator'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='main_title_line1_uz',
            field=models.CharField(default='Special-', max_length=100, null=True, verbose_name='Asosiy sarlavha 1-qator'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='main_title_line2_en',
            field=models.CharField(default='Certificate', max_length=100, null=True, verbose_name='Asosiy sarlavha 2-qator'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='main_title_line2_ru',
            field=models.CharField(default='Certificate', max_length=100, null=True, verbose_name='Asosiy sarlavha 2-qator'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='main_title_line2_uz',
            field=models.CharField(default='Certificate', max_length=100, null=True, verbose_name='Asosiy sarlavha 2-qator'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='main_title_small_en',
            field=models.CharField(default='labaratoriyasi.', max_length=100, null=True, verbose_name='Sarlavha kichik matni'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='main_title_small_ru',
            field=models.CharField(default='labaratoriyasi.', max_length=100, null=True, verbose_name='Sarlavha kichik matni'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='main_title_small_uz',
            field=models.CharField(default='labaratoriyasi.', max_length=100, null=True, verbose_name='Sarlavha kichik matni'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='marquee_text1_en',
            field=models.CharField(default='Special', max_length=50, null=True, verbose_name='Marquee matni 1'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='marquee_text1_ru',
            field=models.CharField(default='Special', max_length=50, null=True, verbose_name='Marquee matni 1'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='marquee_text1_uz',
            field=models.CharField(default='Special', max_length=50, null=True, verbose_name='Marquee matni 1'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='marquee_text2_en',
            field=models.CharField(default='Certificate', max_length=50, null=True, verbose_name='Marquee matni 2'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='marquee_text2_ru',
            field=models.CharField(default='Certificate', max_length=50, null=True, verbose_name='Marquee matni 2'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='marquee_text2_uz',
            field=models.CharField(default='Certificate', max_length=50, null=True, verbose_name='Marquee matni 2'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='scroll_text_en',
            field=models.CharField(default='Pastga', max_length=50, null=True, verbose_name='Scroll tugmasi matni'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='scroll_text_ru',
            field=models.CharField(default='Pastga', max_length=50, null=True, verbose_name='Scroll tugmasi matni'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='scroll_text_uz',
            field=models.CharField(default='Pastga', max_length=50, null=True, verbose_name='Scroll tugmasi matni'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='sub_title_text_en',
            field=models.CharField(default='Qarshi shahridagi', max_length=200, null=True, verbose_name='Sub-sarlavha matni'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='sub_title_text_ru',
            field=models.CharField(default='Qarshi shahridagi', max_length=200, null=True, verbose_name='Sub-sarlavha matni'),
        ),
        migrations.AddField(
            model_name='bannersection',
            name='sub_title_text_uz',
            field=models.CharField(default='Qarshi shahridagi', max_length=200, null=True, verbose_name='Sub-sarlavha matni'),
        ),
        migrations.AddField(
            model_name='certificatecard',
            name='description_en',
            field=models.CharField(blank=True, help_text='Masalan: Sifat kafolatini tasdiqlovchi hujjat', max_length=255, null=True, verbose_name='Sertifikat tavsifi'),
        ),
        migrations.AddField(
            model_name='certificatecard',
            name='description_ru',
            field=models.CharField(blank=True, help_text='Masalan: Sifat kafolatini tasdiqlovchi hujjat', max_length=255, null=True, verbose_name='Sertifikat tavsifi'),
        ),
        migrations.AddField(
            model_name='certificatecard',
            name='description_uz',
            field=models.CharField(blank=True, help_text='Masalan: Sifat kafolatini tasdiqlovchi hujjat', max_length=255, null=True, verbose_name='Sertifikat tavsifi'),
        ),
        migrations.AddField(
            model_name='certificatecard',
            name='title_en',
            field=models.CharField(help_text='Masalan: Akkreditatsiya sertifikati', max_length=255, null=True, verbose_name='Sertifikat nomi'),
        ),
        migrations.AddField(
            model_name='certificatecard',
            name='title_ru',
            field=models.CharField(help_text='Masalan: Akkreditatsiya sertifikati', max_length=255, null=True, verbose_name='Sertifikat nomi'),
        ),
        migrations.AddField(
            model_name='certificatecard',
            name='title_uz',
            field=models.CharField(help_text='Masalan: Akkreditatsiya sertifikati', max_length=255, null=True, verbose_name='Sertifikat nomi'),
        ),
        migrations.AddField(
            model_name='certificatesectionheader',
            name='button_text_en',
            field=models.CharField(default='Barcha sertifikatlar', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='certificatesectionheader',
            name='button_text_ru',
            field=models.CharField(default='Barcha sertifikatlar', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='certificatesectionheader',
            name='button_text_uz',
            field=models.CharField(default='Barcha sertifikatlar', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='certificatesectionheader',
            name='main_title_en',
            field=models.CharField(default='Sifat va ishonchlilikni tasdiqlovchi sertifikatlarimiz', max_length=300, null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='certificatesectionheader',
            name='main_title_ru',
            field=models.CharField(default='Sifat va ishonchlilikni tasdiqlovchi sertifikatlarimiz', max_length=300, null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='certificatesectionheader',
            name='main_title_uz',
            field=models.CharField(default='Sifat va ishonchlilikni tasdiqlovchi sertifikatlarimiz', max_length=300, null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='certificatesectionheader',
            name='sub_title_en',
            field=models.CharField(default='Bizning sertifikatlarimiz', help_text='Masalan: Bizning yutuqlarimiz, Sertifikatlarimiz va hokazo', max_length=200, null=True, verbose_name='Sub-sarlavha'),
        ),
        migrations.AddField(
            model_name='certificatesectionheader',
            name='sub_title_ru',
            field=models.CharField(default='Bizning sertifikatlarimiz', help_text='Masalan: Bizning yutuqlarimiz, Sertifikatlarimiz va hokazo', max_length=200, null=True, verbose_name='Sub-sarlavha'),
        ),
        migrations.AddField(
            model_name='certificatesectionheader',
            name='sub_title_uz',
            field=models.CharField(default='Bizning sertifikatlarimiz', help_text='Masalan: Bizning yutuqlarimiz, Sertifikatlarimiz va hokazo', max_length=200, null=True, verbose_name='Sub-sarlavha'),
        ),
        migrations.AddField(
            model_name='choosecard',
            name='button_text_en',
            field=models.CharField(default='Batafsil', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='choosecard',
            name='button_text_ru',
            field=models.CharField(default='Batafsil', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='choosecard',
            name='button_text_uz',
            field=models.CharField(default='Batafsil', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='choosecard',
            name='description_en',
            field=models.TextField(help_text='Kartochka matni', null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='choosecard',
            name='description_ru',
            field=models.TextField(help_text='Kartochka matni', null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='choosecard',
            name='description_uz',
            field=models.TextField(help_text='Kartochka matni', null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='choosecard',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='choosecard',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='choosecard',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='choosesectionheader',
            name='main_title_en',
            field=models.CharField(default='Nega aynan biz?', max_length=200, null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='choosesectionheader',
            name='main_title_ru',
            field=models.CharField(default='Nega aynan biz?', max_length=200, null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='choosesectionheader',
            name='main_title_uz',
            field=models.CharField(default='Nega aynan biz?', max_length=200, null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='choosesectionheader',
            name='sub_title_en',
            field=models.CharField(default='Maxsus-sertifikat', max_length=200, null=True, verbose_name='Sub-sarlavha'),
        ),
        migrations.AddField(
            model_name='choosesectionheader',
            name='sub_title_ru',
            field=models.CharField(default='Maxsus-sertifikat', max_length=200, null=True, verbose_name='Sub-sarlavha'),
        ),
        migrations.AddField(
            model_name='choosesectionheader',
            name='sub_title_uz',
            field=models.CharField(default='Maxsus-sertifikat', max_length=200, null=True, verbose_name='Sub-sarlavha'),
        ),
        migrations.AddField(
            model_name='clientlogo',
            name='name_en',
            field=models.CharField(help_text='Kompaniya yoki tashkilot nomi', max_length=200, null=True, verbose_name='Mijoz nomi'),
        ),
        migrations.AddField(
            model_name='clientlogo',
            name='name_ru',
            field=models.CharField(help_text='Kompaniya yoki tashkilot nomi', max_length=200, null=True, verbose_name='Mijoz nomi'),
        ),
        migrations.AddField(
            model_name='clientlogo',
            name='name_uz',
            field=models.CharField(help_text='Kompaniya yoki tashkilot nomi', max_length=200, null=True, verbose_name='Mijoz nomi'),
        ),
        migrations.AddField(
            model_name='faqheader',
            name='call_title_en',
            field=models.CharField(default='Bepul konsultatsiya', max_length=150, null=True, verbose_name='Qo‘ng‘iroq sarlavhasi'),
        ),
        migrations.AddField(
            model_name='faqheader',
            name='call_title_ru',
            field=models.CharField(default='Bepul konsultatsiya', max_length=150, null=True, verbose_name='Qo‘ng‘iroq sarlavhasi'),
        ),
        migrations.AddField(
            model_name='faqheader',
            name='call_title_uz',
            field=models.CharField(default='Bepul konsultatsiya', max_length=150, null=True, verbose_name='Qo‘ng‘iroq sarlavhasi'),
        ),
        migrations.AddField(
            model_name='faqheader',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa sarlavha'),
        ),
        migrations.AddField(
            model_name='faqheader',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa sarlavha'),
        ),
        migrations.AddField(
            model_name='faqheader',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa sarlavha'),
        ),
        migrations.AddField(
            model_name='faqheader',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='faqheader',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='faqheader',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='answer_uz',
            field=models.TextField(null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='question_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='question_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='question_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='marqueeitem',
            name='title_en',
            field=models.CharField(help_text='Marquee bo‘limida chiqadigan matn (masalan: Sifat nazorati, Xavfsizlik va hokazo).', max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='marqueeitem',
            name='title_ru',
            field=models.CharField(help_text='Marquee bo‘limida chiqadigan matn (masalan: Sifat nazorati, Xavfsizlik va hokazo).', max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='marqueeitem',
            name='title_uz',
            field=models.CharField(help_text='Marquee bo‘limida chiqadigan matn (masalan: Sifat nazorati, Xavfsizlik va hokazo).', max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='newssectionheader',
            name='button_text_en',
            field=models.CharField(default='Barcha yangiliklar', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='newssectionheader',
            name='button_text_ru',
            field=models.CharField(default='Barcha yangiliklar', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='newssectionheader',
            name='button_text_uz',
            field=models.CharField(default='Barcha yangiliklar', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='newssectionheader',
            name='main_title_en',
            field=models.CharField(default='Bizning markazdagi eng so‘nggi yangiliklardan xabardor bo‘ling', max_length=300, null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='newssectionheader',
            name='main_title_ru',
            field=models.CharField(default='Bizning markazdagi eng so‘nggi yangiliklardan xabardor bo‘ling', max_length=300, null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='newssectionheader',
            name='main_title_uz',
            field=models.CharField(default='Bizning markazdagi eng so‘nggi yangiliklardan xabardor bo‘ling', max_length=300, null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='newssectionheader',
            name='sub_title_en',
            field=models.CharField(default='So‘nggi yangiliklar', help_text='Masalan: Blog, Yangiliklar, O‘quv markazi yangiliklari va hokazo', max_length=200, null=True, verbose_name='Sub-sarlavha'),
        ),
        migrations.AddField(
            model_name='newssectionheader',
            name='sub_title_ru',
            field=models.CharField(default='So‘nggi yangiliklar', help_text='Masalan: Blog, Yangiliklar, O‘quv markazi yangiliklari va hokazo', max_length=200, null=True, verbose_name='Sub-sarlavha'),
        ),
        migrations.AddField(
            model_name='newssectionheader',
            name='sub_title_uz',
            field=models.CharField(default='So‘nggi yangiliklar', help_text='Masalan: Blog, Yangiliklar, O‘quv markazi yangiliklari va hokazo', max_length=200, null=True, verbose_name='Sub-sarlavha'),
        ),
        migrations.AddField(
            model_name='topservice',
            name='description_en',
            field=models.TextField(help_text="Xizmat haqida qisqacha ma'lumot", null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='topservice',
            name='description_ru',
            field=models.TextField(help_text="Xizmat haqida qisqacha ma'lumot", null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='topservice',
            name='description_uz',
            field=models.TextField(help_text="Xizmat haqida qisqacha ma'lumot", null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='topservice',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Xizmat nomi'),
        ),
        migrations.AddField(
            model_name='topservice',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Xizmat nomi'),
        ),
        migrations.AddField(
            model_name='topservice',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Xizmat nomi'),
        ),
        migrations.AddField(
            model_name='topservicesectionheader',
            name='button_text_en',
            field=models.CharField(default='Barcha xizmatlar', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='topservicesectionheader',
            name='button_text_ru',
            field=models.CharField(default='Barcha xizmatlar', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='topservicesectionheader',
            name='button_text_uz',
            field=models.CharField(default='Barcha xizmatlar', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='topservicesectionheader',
            name='main_title_en',
            field=models.CharField(default='Biz taqdim etadigan asosiy xizmatlar', max_length=300, null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='topservicesectionheader',
            name='main_title_ru',
            field=models.CharField(default='Biz taqdim etadigan asosiy xizmatlar', max_length=300, null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='topservicesectionheader',
            name='main_title_uz',
            field=models.CharField(default='Biz taqdim etadigan asosiy xizmatlar', max_length=300, null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='topservicesectionheader',
            name='sub_title_en',
            field=models.CharField(default='Top Servislar', max_length=200, null=True, verbose_name='Sub-sarlavha'),
        ),
        migrations.AddField(
            model_name='topservicesectionheader',
            name='sub_title_ru',
            field=models.CharField(default='Top Servislar', max_length=200, null=True, verbose_name='Sub-sarlavha'),
        ),
        migrations.AddField(
            model_name='topservicesectionheader',
            name='sub_title_uz',
            field=models.CharField(default='Top Servislar', max_length=200, null=True, verbose_name='Sub-sarlavha'),
        ),
    ]
