# Generated by Django 5.2.6 on 2025-10-08 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='Logo')),
                ('mobile_logo', models.ImageField(upload_to='logos/', verbose_name='Mobil Logo')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('email', models.EmailField(max_length=254, verbose_name='Email manzil')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('announcement_text', models.CharField(blank=True, max_length=255, verbose_name="E'lon matni")),
                ('announcement_link', models.URLField(blank=True, verbose_name="E'lon havolasi")),
                ('announcement_active', models.BooleanField(default=True, verbose_name="E'lonni ko'rsatish")),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('search_enabled', models.BooleanField(default=True, verbose_name='Qidiruvni yoqish')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Header Sozlamasi',
                'verbose_name_plural': 'Header Sozlamalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('url', models.CharField(max_length=255, verbose_name='URL manzil')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ikon klassi')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_mega_menu', models.BooleanField(default=False, verbose_name='Mega menyu')),
                ('header_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='settings_app.headersettings', verbose_name='Header sozlamasi')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='settings_app.menuitem', verbose_name='Ota menyu')),
            ],
            options={
                'verbose_name': 'Menyu Elementi',
                'verbose_name_plural': 'Menyu Elementlari',
                'ordering': ['order', 'title'],
            },
        ),
    ]
