# Generated by Django 5.2.6 on 2025-10-08 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Ustun sarlavhasi')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Footer Ustuni',
                'verbose_name_plural': 'Footer Ustunlari',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='footer_logos/', verbose_name='Footer Logo')),
                ('description', models.TextField(help_text='Footer qismidagi qisqacha tavsif', verbose_name='Tavsif')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('email', models.EmailField(max_length=254, verbose_name='Email manzil')),
                ('working_hours', models.CharField(default='Du–Ju: 09:00 – 18:00', max_length=100, verbose_name='Ish vaqti')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('newsletter_title', models.CharField(default="Yangiliklarimizga obuna bo'ling", max_length=255, verbose_name='Newsletter sarlavhasi')),
                ('newsletter_enabled', models.BooleanField(default=True, verbose_name='Newsletter yoqilgan')),
                ('copyright_text', models.CharField(default='Barcha huquqlar himoyalangan.', max_length=255, verbose_name='Copyright matni')),
                ('copyright_link', models.URLField(blank=True, verbose_name='Copyright havolasi')),
                ('award_logo_1', models.ImageField(blank=True, null=True, upload_to='footer_awards/', verbose_name='Award Logo 1')),
                ('award_logo_2', models.ImageField(blank=True, null=True, upload_to='footer_awards/', verbose_name='Award Logo 2')),
                ('show_awards', models.BooleanField(default=True, verbose_name="Award logolarni ko'rsatish")),
                ('show_social_links', models.BooleanField(default=True, verbose_name="Ijtimoiy tarmoqlarni ko'rsatish")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Footer Sozlamasi',
                'verbose_name_plural': 'Footer Sozlamalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('agreed_to_terms', models.BooleanField(default=False, verbose_name='Shartlarga roziman')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Obuna sanasi')),
            ],
            options={
                'verbose_name': 'Newsletter Obunachisi',
                'verbose_name_plural': 'Newsletter Obunachilar',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Havola nomi')),
                ('url', models.CharField(max_length=255, verbose_name='URL manzil')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ikon klassi')),
                ('badge_text', models.CharField(blank=True, help_text='Masalan: Yangi, Hot', max_length=20, verbose_name='Badge matni')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('open_new_tab', models.BooleanField(default=False, verbose_name='Yangi oynada ochish')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='settings_app.footercolumn', verbose_name='Footer ustuni')),
            ],
            options={
                'verbose_name': 'Footer Havolasi',
                'verbose_name_plural': 'Footer Havolalari',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='footercolumn',
            name='footer_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='settings_app.footersettings', verbose_name='Footer sozlamasi'),
        ),
    ]
