# Generated by Django 5.2.6 on 2025-10-08 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_footercolumn_footersettings_newsletter_footerlink_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footercolumn',
            options={'ordering': ['order', 'title'], 'verbose_name': '4. Footer Ustuni', 'verbose_name_plural': '4. Footer Ustunlari'},
        ),
        migrations.AlterModelOptions(
            name='footerlink',
            options={'ordering': ['order', 'title'], 'verbose_name': '5. Footer Havolasi', 'verbose_name_plural': '5. Footer Havolalari'},
        ),
        migrations.AlterModelOptions(
            name='footersettings',
            options={'ordering': ['-created_at'], 'verbose_name': '3. Footer Sozlamasi', 'verbose_name_plural': '3. Footer Sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='headersettings',
            options={'ordering': ['-created_at'], 'verbose_name': '1. Header Sozlamasi', 'verbose_name_plural': '1. Header Sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order', 'title'], 'verbose_name': '2. Menyu', 'verbose_name_plural': '2. Menyular'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-subscribed_at'], 'verbose_name': '6. Newsletter Obunachisi', 'verbose_name_plural': '6. Newsletter Obunachilar'},
        ),
    ]
