# Generated by Django 5.2.6 on 2025-11-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_alter_footercolumn_options_alter_footerlink_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footercolumn',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Ustun sarlavhasi'),
        ),
        migrations.AddField(
            model_name='footercolumn',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Ustun sarlavhasi'),
        ),
        migrations.AddField(
            model_name='footercolumn',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Ustun sarlavhasi'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='badge_text_en',
            field=models.CharField(blank=True, help_text='Masalan: Yangi, Hot', max_length=20, null=True, verbose_name='Badge matni'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='badge_text_ru',
            field=models.CharField(blank=True, help_text='Masalan: Yangi, Hot', max_length=20, null=True, verbose_name='Badge matni'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='badge_text_uz',
            field=models.CharField(blank=True, help_text='Masalan: Yangi, Hot', max_length=20, null=True, verbose_name='Badge matni'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Havola nomi'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Havola nomi'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Havola nomi'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='address_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='copyright_text_en',
            field=models.CharField(default='Barcha huquqlar himoyalangan.', max_length=255, null=True, verbose_name='Copyright matni'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='copyright_text_ru',
            field=models.CharField(default='Barcha huquqlar himoyalangan.', max_length=255, null=True, verbose_name='Copyright matni'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='copyright_text_uz',
            field=models.CharField(default='Barcha huquqlar himoyalangan.', max_length=255, null=True, verbose_name='Copyright matni'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='description_en',
            field=models.TextField(help_text='Footer qismidagi qisqacha tavsif', null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='description_ru',
            field=models.TextField(help_text='Footer qismidagi qisqacha tavsif', null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='description_uz',
            field=models.TextField(help_text='Footer qismidagi qisqacha tavsif', null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='newsletter_title_en',
            field=models.CharField(default="Yangiliklarimizga obuna bo'ling", max_length=255, null=True, verbose_name='Newsletter sarlavhasi'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='newsletter_title_ru',
            field=models.CharField(default="Yangiliklarimizga obuna bo'ling", max_length=255, null=True, verbose_name='Newsletter sarlavhasi'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='newsletter_title_uz',
            field=models.CharField(default="Yangiliklarimizga obuna bo'ling", max_length=255, null=True, verbose_name='Newsletter sarlavhasi'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='working_hours_en',
            field=models.CharField(default='Du–Ju: 09:00 – 18:00', max_length=100, null=True, verbose_name='Ish vaqti'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='working_hours_ru',
            field=models.CharField(default='Du–Ju: 09:00 – 18:00', max_length=100, null=True, verbose_name='Ish vaqti'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='working_hours_uz',
            field=models.CharField(default='Du–Ju: 09:00 – 18:00', max_length=100, null=True, verbose_name='Ish vaqti'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='address_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='announcement_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="E'lon matni"),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='announcement_text_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="E'lon matni"),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='announcement_text_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="E'lon matni"),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
    ]
