# Generated by Django 5.2.6 on 2025-10-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Service', max_length=200, verbose_name='Sarlavha')),
                ('background_image', models.ImageField(upload_to='service/backgrounds/', verbose_name='Fon rasmi')),
                ('overlay_image', models.ImageField(blank=True, null=True, upload_to='service/overlays/', verbose_name='Qatlam rasmi')),
                ('home_link_text', models.CharField(default='Home', max_length=50, verbose_name='Bosh sahifa matni')),
                ('read_more_text', models.CharField(default='Read More', max_length=100, verbose_name='Batafsil tugma matni')),
            ],
            options={
                'verbose_name': 'Xizmatlar sahifasi sarlavhasi',
                'verbose_name_plural': 'Xizmatlar sahifasi sarlavhalari',
            },
        ),
    ]
