# Generated by Django 5.2.6 on 2025-10-16 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (URL uchun)')),
                ('icon', models.CharField(default='tji-service-2', help_text='Masalan: tji-service-2, tji-briefcase', max_length=100, verbose_name='Ikonka klassi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'Xizmat kategoriyasi',
                'verbose_name_plural': 'Xizmat kategoriyalari',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (URL uchun)')),
                ('icon', models.CharField(default='tji-service-2', help_text='Masalan: tji-service-2, tji-briefcase', max_length=100, verbose_name='Ikonka klassi')),
                ('short_description', models.TextField(max_length=500, verbose_name='Qisqa tavsif')),
                ('full_description', models.TextField(verbose_name="To'liq tavsif")),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Xizmat rasmi')),
                ('animation_delay', models.CharField(default='.3s', max_length=10, verbose_name='Animatsiya kechikishi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services_app.servicecategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
