# Generated by Django 5.2.6 on 2025-11-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0002_servicecategory_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='background_image',
            field=models.ImageField(default=1, upload_to='service/backgrounds/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceheader',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='service/backgrounds/', verbose_name='Fon rasmi'),
        ),
    ]
