# Generated by Django 5.2.6 on 2025-11-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0003_service_background_image_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description_en',
            field=models.TextField(null=True, verbose_name="To'liq tavsif"),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description_ru',
            field=models.TextField(null=True, verbose_name="To'liq tavsif"),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description_uz',
            field=models.TextField(null=True, verbose_name="To'liq tavsif"),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_uz',
            field=models.TextField(max_length=500, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='serviceheader',
            name='home_link_text_en',
            field=models.CharField(default='Home', max_length=50, null=True, verbose_name='Bosh sahifa matni'),
        ),
        migrations.AddField(
            model_name='serviceheader',
            name='home_link_text_ru',
            field=models.CharField(default='Home', max_length=50, null=True, verbose_name='Bosh sahifa matni'),
        ),
        migrations.AddField(
            model_name='serviceheader',
            name='home_link_text_uz',
            field=models.CharField(default='Home', max_length=50, null=True, verbose_name='Bosh sahifa matni'),
        ),
        migrations.AddField(
            model_name='serviceheader',
            name='read_more_text_en',
            field=models.CharField(default='Read More', max_length=100, null=True, verbose_name='Batafsil tugma matni'),
        ),
        migrations.AddField(
            model_name='serviceheader',
            name='read_more_text_ru',
            field=models.CharField(default='Read More', max_length=100, null=True, verbose_name='Batafsil tugma matni'),
        ),
        migrations.AddField(
            model_name='serviceheader',
            name='read_more_text_uz',
            field=models.CharField(default='Read More', max_length=100, null=True, verbose_name='Batafsil tugma matni'),
        ),
        migrations.AddField(
            model_name='serviceheader',
            name='title_en',
            field=models.CharField(default='Service', max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='serviceheader',
            name='title_ru',
            field=models.CharField(default='Service', max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='serviceheader',
            name='title_uz',
            field=models.CharField(default='Service', max_length=200, null=True, verbose_name='Sarlavha'),
        ),
    ]
