# Generated by Django 5.2.6 on 2025-10-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Blog Right Sidebar', max_length=200, verbose_name='Sarlavha')),
                ('background_image', models.ImageField(upload_to='news/backgrounds/', verbose_name='Fon rasmi')),
                ('overlay_image', models.ImageField(blank=True, null=True, upload_to='news/overlays/', verbose_name='Qatlam rasmi')),
                ('home_link_text', models.CharField(default='Home', max_length=50, verbose_name='Bosh sahifa matni')),
            ],
            options={
                'verbose_name': 'Yangiliklar sahifasi sarlavhasi',
                'verbose_name_plural': 'Yangiliklar sahifasi sarlavhalari',
            },
        ),
    ]
