# Generated by Django 5.2.6 on 2025-10-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_newsheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsStaticTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=200, verbose_name='Qidiruv matni')),
                ('latest_news', models.CharField(max_length=200, verbose_name='Oxirgi yangiliklar matni')),
                ('categories', models.CharField(max_length=200, verbose_name='Kategoriyalar matni')),
            ],
            options={
                'verbose_name': 'Yangiliklar sahifasi static matn',
                'verbose_name_plural': 'Yangiliklar sahifasi static matnlar',
            },
        ),
    ]
