# Generated by Django 5.2.6 on 2025-10-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_newsstatictexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstatictexts',
            name='read_more_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Oxirgi yangiliklar matni'),
        ),
    ]
