# Generated by Django 5.2.6 on 2025-11-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_newsstatictexts_read_more_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(null=True, verbose_name='To‘liq matn'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='To‘liq matn'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='To‘liq matn'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_uz',
            field=models.TextField(max_length=500, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='newsheader',
            name='home_link_text_en',
            field=models.CharField(default='Home', max_length=50, null=True, verbose_name='Bosh sahifa matni'),
        ),
        migrations.AddField(
            model_name='newsheader',
            name='home_link_text_ru',
            field=models.CharField(default='Home', max_length=50, null=True, verbose_name='Bosh sahifa matni'),
        ),
        migrations.AddField(
            model_name='newsheader',
            name='home_link_text_uz',
            field=models.CharField(default='Home', max_length=50, null=True, verbose_name='Bosh sahifa matni'),
        ),
        migrations.AddField(
            model_name='newsheader',
            name='title_en',
            field=models.CharField(default='Blog Right Sidebar', max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='newsheader',
            name='title_ru',
            field=models.CharField(default='Blog Right Sidebar', max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='newsheader',
            name='title_uz',
            field=models.CharField(default='Blog Right Sidebar', max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='newsstatictexts',
            name='categories_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Kategoriyalar matni'),
        ),
        migrations.AddField(
            model_name='newsstatictexts',
            name='categories_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Kategoriyalar matni'),
        ),
        migrations.AddField(
            model_name='newsstatictexts',
            name='categories_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Kategoriyalar matni'),
        ),
        migrations.AddField(
            model_name='newsstatictexts',
            name='latest_news_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Oxirgi yangiliklar matni'),
        ),
        migrations.AddField(
            model_name='newsstatictexts',
            name='latest_news_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Oxirgi yangiliklar matni'),
        ),
        migrations.AddField(
            model_name='newsstatictexts',
            name='latest_news_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Oxirgi yangiliklar matni'),
        ),
        migrations.AddField(
            model_name='newsstatictexts',
            name='read_more_text_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Oxirgi yangiliklar matni'),
        ),
        migrations.AddField(
            model_name='newsstatictexts',
            name='read_more_text_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Oxirgi yangiliklar matni'),
        ),
        migrations.AddField(
            model_name='newsstatictexts',
            name='read_more_text_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Oxirgi yangiliklar matni'),
        ),
        migrations.AddField(
            model_name='newsstatictexts',
            name='search_text_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Qidiruv matni'),
        ),
        migrations.AddField(
            model_name='newsstatictexts',
            name='search_text_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Qidiruv matni'),
        ),
        migrations.AddField(
            model_name='newsstatictexts',
            name='search_text_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Qidiruv matni'),
        ),
    ]
