# Generated by Django 5.2.6 on 2025-10-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_about', models.CharField(max_length=200, verbose_name='About sahifasi sarlavhasi')),
                ('title_home', models.CharField(max_length=200, verbose_name='Bosh sahifa sarlavhasi')),
            ],
            options={
                'verbose_name': 'About Sahifa sarlavhasi',
                'verbose_name_plural': 'About Sahifa sarlavhalari',
            },
        ),
    ]
