# Generated by Django 5.2.6 on 2025-10-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagetitle',
            name='client_text',
            field=models.TextField(blank=True, null=True, verbose_name='Client logo text'),
        ),
    ]
