# Generated by Django 5.2.6 on 2025-10-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0002_aboutpagetitle_client_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name="To'liq ismi")),
                ('designation', models.CharField(max_length=100, verbose_name='Lavozimi')),
                ('image', models.ImageField(upload_to='team/', verbose_name='Rasm')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Jamoa A'zosi",
                'verbose_name_plural': "Jamoa A'zolari",
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(default='Meet Our Team', max_length=100, verbose_name='Sub Title')),
                ('main_title', models.CharField(default='Success Stories Fuel our Innovation.', max_length=200, verbose_name='Main Title')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Section',
                'verbose_name_plural': 'Team Section',
                'ordering': ['-created_at'],
            },
        ),
    ]
