# Generated by Django 5.2.6 on 2025-10-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0003_teammember_teamsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagetitle',
            options={'verbose_name': '1. About Sahifa sarlavhasi', 'verbose_name_plural': '1. About Sahifa sarlavhalari'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', '-created_at'], 'verbose_name': "3. Jamoa A'zosi", 'verbose_name_plural': "3. Jamoa A'zolari"},
        ),
        migrations.AlterModelOptions(
            name='teamsection',
            options={'ordering': ['-created_at'], 'verbose_name': "2. Jamoa bo'limi sarlavhasi", 'verbose_name_plural': "2. Jamoa bo'limi sarlavhasi"},
        ),
    ]
