# Generated by Django 5.2.6 on 2025-10-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0004_alter_aboutpagetitle_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact Us', max_length=200, verbose_name='Sarlavha')),
                ('background_image', models.ImageField(upload_to='contact/backgrounds/', verbose_name='Fon rasmi')),
                ('overlay_image', models.ImageField(blank=True, null=True, upload_to='contact/overlays/', verbose_name='Qatlam rasmi')),
                ('home_link_text', models.CharField(default='Home', max_length=50, verbose_name='Bosh sahifa matni')),
            ],
            options={
                'verbose_name': '4. Aloqa sahifasi sarlavhasi',
                'verbose_name_plural': '4. Aloqa sahifasi sarlavhalari',
            },
        ),
    ]
