# Generated by Django 5.2.6 on 2025-10-16 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0005_contactheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default="Aloqa ma'lumotlari", max_length=100, verbose_name='Kichik sarlavha')),
                ('title', models.CharField(default="Biz bilan bog'laning", max_length=200, verbose_name='Asosiy sarlavha')),
                ('title_highlight', models.CharField(default='Biz', help_text="Sarlavhadagi rang bilan ajratilgan so'z", max_length=100, verbose_name="Ajratilgan so'z")),
            ],
            options={
                'verbose_name': "Aloqa ma'lumotlari bo'limi",
                'verbose_name_plural': "Aloqa ma'lumotlari bo'limlari",
            },
        ),
        migrations.CreateModel(
            name='ContactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('tji-location-3', 'Manzil'), ('tji-envelop', 'Email'), ('tji-phone', 'Telefon'), ('tji-chat', 'Chat')], max_length=50, verbose_name='Ikonka')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, help_text='Manzil uchun ishlatiladi', null=True, verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('animation_delay', models.CharField(default='.3s', max_length=10, verbose_name='Animatsiya kechikishi')),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages_app.contactinfo', verbose_name="Aloqa ma'lumotlari")),
            ],
            options={
                'verbose_name': 'Aloqa elementi',
                'verbose_name_plural': 'Aloqa elementlari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('email', 'Email'), ('tel', 'Telefon'), ('url', 'Havola')], max_length=20, verbose_name='Havola turi')),
                ('link_value', models.CharField(help_text='Email, telefon raqami yoki URL', max_length=200, verbose_name='Havola qiymati')),
                ('display_text', models.CharField(max_length=200, verbose_name="Ko'rsatiladigan matn")),
                ('is_active', models.BooleanField(default=False, help_text="Active klassini qo'shish uchun", verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('contact_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pages_app.contactitem', verbose_name='Aloqa elementi')),
            ],
            options={
                'verbose_name': 'Aloqa elementi tafsiloti',
                'verbose_name_plural': 'Aloqa elementi tafsilotlari',
                'ordering': ['order'],
            },
        ),
    ]
