# Generated by Django 5.2.6 on 2025-10-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0006_contactinfo_contactitem_contactitemdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': "4. Aloqa ma'lumotlari bo'limi", 'verbose_name_plural': "4. Aloqa ma'lumotlari bo'limlari"},
        ),
        migrations.AlterModelOptions(
            name='contactitem',
            options={'ordering': ['order'], 'verbose_name': '4. Aloqa elementi', 'verbose_name_plural': '4. Aloqa elementlari'},
        ),
        migrations.AlterModelOptions(
            name='contactitemdetail',
            options={'ordering': ['order'], 'verbose_name': '4. Aloqa elementi tafsiloti', 'verbose_name_plural': '4. Aloqa elementi tafsilotlari'},
        ),
    ]
