# Generated by Django 5.2.6 on 2025-10-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0007_alter_contactinfo_options_alter_contactitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqti')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
            ],
            options={
                'verbose_name': 'Aloqa formasi',
                'verbose_name_plural': 'Aloqa formalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactFormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Biz bilan bog'laning yoki bizning manzilimizga tashrif buyuring", max_length=300, verbose_name='Sarlavha')),
                ('map_url', models.URLField(help_text='Google Maps embed URL', verbose_name='Xarita URL')),
                ('animation_delay', models.CharField(default='.1s', max_length=10, verbose_name='Forma animatsiya kechikishi')),
                ('map_animation_delay', models.CharField(default='.3s', max_length=10, verbose_name='Xarita animatsiya kechikishi')),
            ],
            options={
                'verbose_name': 'Aloqa formasi sozlamalari',
                'verbose_name_plural': 'Aloqa formasi sozlamalari',
            },
        ),
    ]
