# Generated by Django 5.2.6 on 2025-10-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0008_contactform_contactformsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['-created_at'], 'verbose_name': '4. Aloqa formasi', 'verbose_name_plural': '4. Aloqa formalari'},
        ),
        migrations.AlterModelOptions(
            name='contactformsettings',
            options={'verbose_name': '4. Aloqa formasi sozlamalari', 'verbose_name_plural': '4. Aloqa formasi sozlamalari'},
        ),
    ]
