# Generated by Django 5.2.6 on 2025-10-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0009_alter_contactform_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformsettings',
            name='email_label',
            field=models.CharField(default='Email Address', max_length=100, verbose_name='Email maydon nomi'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='error_message',
            field=models.CharField(default='Please fill in all required fields!', max_length=200, verbose_name='Xato xabari'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='full_name_label',
            field=models.CharField(default='Full Name', max_length=100, verbose_name='Ism maydon nomi'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='message_label',
            field=models.CharField(default='Type message', max_length=100, verbose_name='Xabar maydon nomi'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='phone_label',
            field=models.CharField(default='Phone Number', max_length=100, verbose_name='Telefon maydon nomi'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='submit_button_text',
            field=models.CharField(default='Submit Now', max_length=100, verbose_name='Yuborish tugmasi matni'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='success_message',
            field=models.CharField(default='Your message has been sent successfully!', max_length=200, verbose_name='Muvaffaqiyatli xabar'),
        ),
        migrations.AlterField(
            model_name='contactformsettings',
            name='title',
            field=models.CharField(default='Feel Free to Get in Touch or Visit our Location', max_length=300, verbose_name='Sarlavha'),
        ),
    ]
