# Generated by Django 5.2.6 on 2025-10-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0010_contactformsettings_email_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtaSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Let's Build Future Together.", max_length=300, verbose_name='Sarlavha')),
                ('button_text', models.CharField(default='Get Started Now', max_length=100, verbose_name='Tugma matni')),
                ('button_link', models.CharField(default='contact.html', max_length=200, verbose_name='Tugma havolasi')),
                ('background_image', models.ImageField(upload_to='cta/', verbose_name='Fon rasmi')),
                ('animation_delay', models.CharField(default='.6s', max_length=10, verbose_name='Animatsiya kechikishi')),
            ],
            options={
                'verbose_name': "4. CTA bo'limi",
                'verbose_name_plural': "4. CTA bo'limlari",
            },
        ),
    ]
