# Generated by Django 5.2.6 on 2025-11-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0011_ctasection'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagetitle',
            name='client_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Client logo text'),
        ),
        migrations.AddField(
            model_name='aboutpagetitle',
            name='client_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Client logo text'),
        ),
        migrations.AddField(
            model_name='aboutpagetitle',
            name='client_text_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Client logo text'),
        ),
        migrations.AddField(
            model_name='aboutpagetitle',
            name='title_about_en',
            field=models.CharField(max_length=200, null=True, verbose_name='About sahifasi sarlavhasi'),
        ),
        migrations.AddField(
            model_name='aboutpagetitle',
            name='title_about_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='About sahifasi sarlavhasi'),
        ),
        migrations.AddField(
            model_name='aboutpagetitle',
            name='title_about_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='About sahifasi sarlavhasi'),
        ),
        migrations.AddField(
            model_name='aboutpagetitle',
            name='title_home_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Bosh sahifa sarlavhasi'),
        ),
        migrations.AddField(
            model_name='aboutpagetitle',
            name='title_home_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Bosh sahifa sarlavhasi'),
        ),
        migrations.AddField(
            model_name='aboutpagetitle',
            name='title_home_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Bosh sahifa sarlavhasi'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='email_label_en',
            field=models.CharField(default='Email Address', max_length=100, null=True, verbose_name='Email maydon nomi'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='email_label_ru',
            field=models.CharField(default='Email Address', max_length=100, null=True, verbose_name='Email maydon nomi'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='email_label_uz',
            field=models.CharField(default='Email Address', max_length=100, null=True, verbose_name='Email maydon nomi'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='error_message_en',
            field=models.CharField(default='Please fill in all required fields!', max_length=200, null=True, verbose_name='Xato xabari'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='error_message_ru',
            field=models.CharField(default='Please fill in all required fields!', max_length=200, null=True, verbose_name='Xato xabari'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='error_message_uz',
            field=models.CharField(default='Please fill in all required fields!', max_length=200, null=True, verbose_name='Xato xabari'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='full_name_label_en',
            field=models.CharField(default='Full Name', max_length=100, null=True, verbose_name='Ism maydon nomi'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='full_name_label_ru',
            field=models.CharField(default='Full Name', max_length=100, null=True, verbose_name='Ism maydon nomi'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='full_name_label_uz',
            field=models.CharField(default='Full Name', max_length=100, null=True, verbose_name='Ism maydon nomi'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='message_label_en',
            field=models.CharField(default='Type message', max_length=100, null=True, verbose_name='Xabar maydon nomi'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='message_label_ru',
            field=models.CharField(default='Type message', max_length=100, null=True, verbose_name='Xabar maydon nomi'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='message_label_uz',
            field=models.CharField(default='Type message', max_length=100, null=True, verbose_name='Xabar maydon nomi'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='phone_label_en',
            field=models.CharField(default='Phone Number', max_length=100, null=True, verbose_name='Telefon maydon nomi'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='phone_label_ru',
            field=models.CharField(default='Phone Number', max_length=100, null=True, verbose_name='Telefon maydon nomi'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='phone_label_uz',
            field=models.CharField(default='Phone Number', max_length=100, null=True, verbose_name='Telefon maydon nomi'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='submit_button_text_en',
            field=models.CharField(default='Submit Now', max_length=100, null=True, verbose_name='Yuborish tugmasi matni'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='submit_button_text_ru',
            field=models.CharField(default='Submit Now', max_length=100, null=True, verbose_name='Yuborish tugmasi matni'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='submit_button_text_uz',
            field=models.CharField(default='Submit Now', max_length=100, null=True, verbose_name='Yuborish tugmasi matni'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='success_message_en',
            field=models.CharField(default='Your message has been sent successfully!', max_length=200, null=True, verbose_name='Muvaffaqiyatli xabar'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='success_message_ru',
            field=models.CharField(default='Your message has been sent successfully!', max_length=200, null=True, verbose_name='Muvaffaqiyatli xabar'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='success_message_uz',
            field=models.CharField(default='Your message has been sent successfully!', max_length=200, null=True, verbose_name='Muvaffaqiyatli xabar'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='title_en',
            field=models.CharField(default='Feel Free to Get in Touch or Visit our Location', max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='title_ru',
            field=models.CharField(default='Feel Free to Get in Touch or Visit our Location', max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='title_uz',
            field=models.CharField(default='Feel Free to Get in Touch or Visit our Location', max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='contactheader',
            name='home_link_text_en',
            field=models.CharField(default='Home', max_length=50, null=True, verbose_name='Bosh sahifa matni'),
        ),
        migrations.AddField(
            model_name='contactheader',
            name='home_link_text_ru',
            field=models.CharField(default='Home', max_length=50, null=True, verbose_name='Bosh sahifa matni'),
        ),
        migrations.AddField(
            model_name='contactheader',
            name='home_link_text_uz',
            field=models.CharField(default='Home', max_length=50, null=True, verbose_name='Bosh sahifa matni'),
        ),
        migrations.AddField(
            model_name='contactheader',
            name='title_en',
            field=models.CharField(default='Contact Us', max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='contactheader',
            name='title_ru',
            field=models.CharField(default='Contact Us', max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='contactheader',
            name='title_uz',
            field=models.CharField(default='Contact Us', max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='subtitle_en',
            field=models.CharField(default="Aloqa ma'lumotlari", max_length=100, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='subtitle_ru',
            field=models.CharField(default="Aloqa ma'lumotlari", max_length=100, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='subtitle_uz',
            field=models.CharField(default="Aloqa ma'lumotlari", max_length=100, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='title_en',
            field=models.CharField(default="Biz bilan bog'laning", max_length=200, null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='title_highlight_en',
            field=models.CharField(default='Biz', help_text="Sarlavhadagi rang bilan ajratilgan so'z", max_length=100, null=True, verbose_name="Ajratilgan so'z"),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='title_highlight_ru',
            field=models.CharField(default='Biz', help_text="Sarlavhadagi rang bilan ajratilgan so'z", max_length=100, null=True, verbose_name="Ajratilgan so'z"),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='title_highlight_uz',
            field=models.CharField(default='Biz', help_text="Sarlavhadagi rang bilan ajratilgan so'z", max_length=100, null=True, verbose_name="Ajratilgan so'z"),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='title_ru',
            field=models.CharField(default="Biz bilan bog'laning", max_length=200, null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='title_uz',
            field=models.CharField(default="Biz bilan bog'laning", max_length=200, null=True, verbose_name='Asosiy sarlavha'),
        ),
        migrations.AddField(
            model_name='contactitem',
            name='description_en',
            field=models.TextField(blank=True, help_text='Manzil uchun ishlatiladi', null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='contactitem',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Manzil uchun ishlatiladi', null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='contactitem',
            name='description_uz',
            field=models.TextField(blank=True, help_text='Manzil uchun ishlatiladi', null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='contactitem',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='contactitem',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='contactitem',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='contactitemdetail',
            name='display_text_en',
            field=models.CharField(max_length=200, null=True, verbose_name="Ko'rsatiladigan matn"),
        ),
        migrations.AddField(
            model_name='contactitemdetail',
            name='display_text_ru',
            field=models.CharField(max_length=200, null=True, verbose_name="Ko'rsatiladigan matn"),
        ),
        migrations.AddField(
            model_name='contactitemdetail',
            name='display_text_uz',
            field=models.CharField(max_length=200, null=True, verbose_name="Ko'rsatiladigan matn"),
        ),
        migrations.AddField(
            model_name='ctasection',
            name='button_text_en',
            field=models.CharField(default='Get Started Now', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='ctasection',
            name='button_text_ru',
            field=models.CharField(default='Get Started Now', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='ctasection',
            name='button_text_uz',
            field=models.CharField(default='Get Started Now', max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='ctasection',
            name='title_en',
            field=models.CharField(default="Let's Build Future Together.", max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ctasection',
            name='title_ru',
            field=models.CharField(default="Let's Build Future Together.", max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ctasection',
            name='title_uz',
            field=models.CharField(default="Let's Build Future Together.", max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='designation_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='designation_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='designation_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name="To'liq ismi"),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name="To'liq ismi"),
        ),
        migrations.AddField(
            model_name='teammember',
            name='full_name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name="To'liq ismi"),
        ),
        migrations.AddField(
            model_name='teamsection',
            name='main_title_en',
            field=models.CharField(default='Success Stories Fuel our Innovation.', max_length=200, null=True, verbose_name='Main Title'),
        ),
        migrations.AddField(
            model_name='teamsection',
            name='main_title_ru',
            field=models.CharField(default='Success Stories Fuel our Innovation.', max_length=200, null=True, verbose_name='Main Title'),
        ),
        migrations.AddField(
            model_name='teamsection',
            name='main_title_uz',
            field=models.CharField(default='Success Stories Fuel our Innovation.', max_length=200, null=True, verbose_name='Main Title'),
        ),
        migrations.AddField(
            model_name='teamsection',
            name='sub_title_en',
            field=models.CharField(default='Meet Our Team', max_length=100, null=True, verbose_name='Sub Title'),
        ),
        migrations.AddField(
            model_name='teamsection',
            name='sub_title_ru',
            field=models.CharField(default='Meet Our Team', max_length=100, null=True, verbose_name='Sub Title'),
        ),
        migrations.AddField(
            model_name='teamsection',
            name='sub_title_uz',
            field=models.CharField(default='Meet Our Team', max_length=100, null=True, verbose_name='Sub Title'),
        ),
    ]
