# Generated by Django 5.2.6 on 2025-11-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0012_aboutpagetitle_client_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagetitle',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/about/'),
        ),
    ]
