# Generated by Django 5.2.6 on 2025-11-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0013_aboutpagetitle_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsettings',
            name='map_url',
            field=models.TextField(blank=True, help_text='Google Maps embed URL', null=True, verbose_name='Xarita URL'),
        ),
    ]
